---

clusternet:
    type: module
    module: /vccjs/clusternet.js
    class: ClusterNet

clusterdns:
    type: module
    module: /vccjs/clusterdns.js
    class: ClusterDNS
    requires: clusternet

clusternode:
    type: module
    module: /vccjs/clusternode.js
    class: ClusterNode
    requires: clusterdns

clusterwatcher:
    type: module
    module: /vccjs/clusterwatcher.js
    class: ClusterWatcher
    requires: clusternode